/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_;

import karate_project.CConexion;
import karate_project.Seccion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class Ingresar_Seccion extends javax.swing.JFrame {

    /**
     * Creates new form Ingresar_Seccion
     */
    public Ingresar_Seccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelR_Ent = new javax.swing.JLabel();
        jLabelIng_ID = new javax.swing.JLabel();
        jLabelIng_Horario = new javax.swing.JLabel();
        jLabelIng_Cedula1 = new javax.swing.JLabel();
        jLabelIng_Cedula2 = new javax.swing.JLabel();
        Ing_Ancho = new javax.swing.JTextField();
        Ing_ID = new javax.swing.JTextField();
        Ing_Alto = new javax.swing.JTextField();
        Ing_Largo = new javax.swing.JTextField();
        Ing_Entre = new javax.swing.JButton();
        Ing_Categoria = new javax.swing.JTextField();
        Ing_Capacidad = new javax.swing.JTextField();
        jLabelIng_Cedula3 = new javax.swing.JLabel();
        jLabelIng_Horario1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelR_Ent.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelR_Ent.setText("Ingresa Datos de Seccion ");
        jPanelFondo.add(jLabelR_Ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 33));

        jLabelIng_ID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_ID.setText("Ingrese ID");
        jPanelFondo.add(jLabelIng_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabelIng_Horario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Horario.setText("Ingrese Ancho");
        jPanelFondo.add(jLabelIng_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabelIng_Cedula1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula1.setText("Ingrese Alto");
        jPanelFondo.add(jLabelIng_Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabelIng_Cedula2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula2.setText("Ingrese Largo");
        jPanelFondo.add(jLabelIng_Cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        Ing_Ancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_AnchoActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Ancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 210, -1));

        Ing_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_IDActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, -1));

        Ing_Alto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_AltoActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Alto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 210, -1));

        Ing_Largo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_LargoActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Largo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));

        Ing_Entre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ing_Entre.setText("Ingresar");
        Ing_Entre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_EntreActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Entre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        Ing_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_CategoriaActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 210, -1));

        Ing_Capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_CapacidadActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 210, -1));

        jLabelIng_Cedula3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula3.setText("Ingrese Capacidad");
        jPanelFondo.add(jLabelIng_Cedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabelIng_Horario1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Horario1.setText("Categoria");
        jPanelFondo.add(jLabelIng_Horario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        Regresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanelFondo.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ing_AnchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_AnchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_AnchoActionPerformed

    private void Ing_AltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_AltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_AltoActionPerformed

    private void Ing_LargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_LargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_LargoActionPerformed

    private void Ing_EntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_EntreActionPerformed

       
            int ID = Integer.parseInt(Ing_ID.getText());
            double alto = Double.parseDouble(Ing_Alto.getText());
            double largo = Double.parseDouble(Ing_Largo.getText());
            double ancho = Double.parseDouble(Ing_Ancho.getText());
            int capacidad = Integer.parseInt(Ing_Capacidad.getText());
            String categoria = Ing_Categoria.getText();
            Seccion sec = new Seccion(ID, alto, largo, ancho, capacidad, categoria);
            sec.IngresarSeccion();
        

    }//GEN-LAST:event_Ing_EntreActionPerformed

    private void Ing_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_CategoriaActionPerformed

    private void Ing_CapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_CapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_CapacidadActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Menu_Principal men = new Menu_Principal();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void Ing_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingresar_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingresar_Seccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ing_Alto;
    private javax.swing.JTextField Ing_Ancho;
    private javax.swing.JTextField Ing_Capacidad;
    private javax.swing.JTextField Ing_Categoria;
    private javax.swing.JButton Ing_Entre;
    private javax.swing.JTextField Ing_ID;
    private javax.swing.JTextField Ing_Largo;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabelIng_Cedula1;
    private javax.swing.JLabel jLabelIng_Cedula2;
    private javax.swing.JLabel jLabelIng_Cedula3;
    private javax.swing.JLabel jLabelIng_Horario;
    private javax.swing.JLabel jLabelIng_Horario1;
    private javax.swing.JLabel jLabelIng_ID;
    private javax.swing.JLabel jLabelR_Ent;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
