/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Insert_Seccion = new javax.swing.JButton();
        Insert_Cliente = new javax.swing.JButton();
        Del_Entrenador = new javax.swing.JButton();
        Insert_Entrenador = new javax.swing.JButton();
        Del_Cliente = new javax.swing.JButton();
        Del_Seccion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Clases de Karate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 380, 40));

        Insert_Seccion.setBackground(new java.awt.Color(204, 255, 204));
        Insert_Seccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Insert_Seccion.setText("Registrar Seccion");
        Insert_Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_SeccionActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_Seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        Insert_Cliente.setBackground(new java.awt.Color(204, 255, 204));
        Insert_Cliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Insert_Cliente.setText("Registrar Cliente");
        Insert_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        Del_Entrenador.setBackground(new java.awt.Color(204, 255, 204));
        Del_Entrenador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Del_Entrenador.setText("Editar");
        Del_Entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_EntrenadorActionPerformed(evt);
            }
        });
        getContentPane().add(Del_Entrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        Insert_Entrenador.setBackground(new java.awt.Color(204, 255, 204));
        Insert_Entrenador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Insert_Entrenador.setText("Registrar Entrenador");
        Insert_Entrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_EntrenadorActionPerformed(evt);
            }
        });
        getContentPane().add(Insert_Entrenador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        Del_Cliente.setBackground(new java.awt.Color(204, 255, 204));
        Del_Cliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Del_Cliente.setText("Editar");
        Del_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(Del_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        Del_Seccion.setBackground(new java.awt.Color(204, 255, 204));
        Del_Seccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Del_Seccion.setText("Editar");
        Del_Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_SeccionActionPerformed(evt);
            }
        });
        getContentPane().add(Del_Seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image_/karateimage.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insert_SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_SeccionActionPerformed
        Ingresar_Seccion scc = new Ingresar_Seccion();
        scc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Insert_SeccionActionPerformed

    private void Insert_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_ClienteActionPerformed
        Insertar_Cliente cli = new Insertar_Cliente();
        cli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Insert_ClienteActionPerformed

    private void Del_EntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_EntrenadorActionPerformed
        Mostrar_Eliminar_Entrenador mee = new Mostrar_Eliminar_Entrenador();
        mee.setVisible(true);
        try {
            mee.ListarMenu("SELECT * FROM ENTRENADOR;");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_Del_EntrenadorActionPerformed

    private void Insert_EntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_EntrenadorActionPerformed
        Insertar_Entrenador ent = new Insertar_Entrenador();
        ent.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Insert_EntrenadorActionPerformed

    private void Del_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_ClienteActionPerformed
        Mostrar_Eliminar_Cliente mec = new Mostrar_Eliminar_Cliente();
        mec.setVisible(true);
        try {
            mec.ListarMenu("SELECT * FROM CLIENTE;");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_Del_ClienteActionPerformed

    private void Del_SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_SeccionActionPerformed
        Mostrar_Eliminar_Seccion mes = new Mostrar_Eliminar_Seccion();
        mes.setVisible(true);
        try {
            mes.ListarMenu("SELECT * FROM SECCION;");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_Del_SeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Del_Cliente;
    private javax.swing.JButton Del_Entrenador;
    private javax.swing.JButton Del_Seccion;
    private javax.swing.JButton Insert_Cliente;
    private javax.swing.JButton Insert_Entrenador;
    private javax.swing.JButton Insert_Seccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
