/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_;

import karate_project.CConexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin
 */
public class Mostrar_Eliminar_Entrenador extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar_Eliminar_Entrenador
     */
    public Mostrar_Eliminar_Entrenador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void ListarMenu(String Sql) throws SQLException {
        ID.removeAllItems();
        ArrayList<Integer> IDM = new ArrayList<>();
        ArrayList<String> Info = new ArrayList<>();
        DefaultListModel Modelo = new DefaultListModel();
        CConexion con = new CConexion();
        con.Establecer_conexion();
        ResultSet RSE = con.Consulta(Sql);
        while (RSE.next()) {
            IDM.add(RSE.getInt(1));
            Info.add("- Cedula:"+RSE.getString(2) + ", Sueldo:" + RSE.getDouble(3)+", Horario:"+RSE.getString(4));
        }
        for (int i = 0; i < IDM.size(); i++) {
            String anidar = "ID: " + IDM.get(i) + " " + Info.get(i);
            ID.addItem(Integer.toString(IDM.get(i)));
            Modelo.add(i, anidar);
        }
        Lista_Entrenador.setModel(Modelo);
        con.CerrarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Entrenador = new javax.swing.JList<>();
        Regresar = new javax.swing.JButton();
        EntDel = new javax.swing.JButton();
        ID = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(Lista_Entrenador);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 481, 222));

        Regresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        EntDel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        EntDel.setText("Eliminar");
        EntDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntDelActionPerformed(evt);
            }
        });
        jPanel1.add(EntDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 73, -1));

        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 70, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntDelActionPerformed
      CConexion con = new CConexion();
        try {
            con.Establecer_conexion();
            con.actualizarBD("DELETE FROM ENTRENADOR WHERE IdEntrenador ="+(String)ID.getSelectedItem()+";");
            ListarMenu("SELECT * FROM ENTRENADOR;");
            con.CerrarBD();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EntDelActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Menu_Principal men = new Menu_Principal();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Upd_Entrenador upd = new Upd_Entrenador();
        upd.setVisible(true);
        upd.getID(Integer.parseInt((String) ID.getSelectedItem()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Eliminar_Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Eliminar_Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Eliminar_Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Eliminar_Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_Eliminar_Entrenador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntDel;
    private javax.swing.JComboBox<String> ID;
    private javax.swing.JList<String> Lista_Entrenador;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
