/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_;

import karate_project.CConexion;
import karate_project.Seccion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class Upd_Seccion extends javax.swing.JFrame {

    /**
     * Creates new form Upd_Seccion
     */
    public Upd_Seccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    int ID;

    public void getID(int a) {
        ID = a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelR_Ent = new javax.swing.JLabel();
        jLabelIng_Horario = new javax.swing.JLabel();
        jLabelIng_Cedula1 = new javax.swing.JLabel();
        jLabelIng_Cedula2 = new javax.swing.JLabel();
        Ing_Ancho_up = new javax.swing.JTextField();
        Ing_Alto_up = new javax.swing.JTextField();
        Ing_Largo_up = new javax.swing.JTextField();
        Ing_Act = new javax.swing.JButton();
        Ing_Categoria_up = new javax.swing.JTextField();
        Ing_Capacidad_up = new javax.swing.JTextField();
        jLabelIng_Cedula3 = new javax.swing.JLabel();
        jLabelIng_Horario1 = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelR_Ent.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelR_Ent.setText("Actualizar Datos de Seccion ");
        jPanelFondo.add(jLabelR_Ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 33));

        jLabelIng_Horario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Horario.setText("Ingrese Ancho");
        jPanelFondo.add(jLabelIng_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabelIng_Cedula1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula1.setText("Ingrese Alto");
        jPanelFondo.add(jLabelIng_Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabelIng_Cedula2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula2.setText("Ingrese Largo");
        jPanelFondo.add(jLabelIng_Cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        Ing_Ancho_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Ancho_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Ancho_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, -1));

        Ing_Alto_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Alto_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Alto_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 210, -1));

        Ing_Largo_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Largo_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Largo_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 210, -1));

        Ing_Act.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ing_Act.setText("Actualizar");
        Ing_Act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_ActActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Act, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        Ing_Categoria_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Categoria_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Categoria_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 210, -1));

        Ing_Capacidad_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Capacidad_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Capacidad_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, -1));

        jLabelIng_Cedula3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula3.setText("Ingrese Capacidad");
        jPanelFondo.add(jLabelIng_Cedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabelIng_Horario1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Horario1.setText("Categoria");
        jPanelFondo.add(jLabelIng_Horario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Regresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanelFondo.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 333));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ing_Ancho_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Ancho_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Ancho_upActionPerformed

    private void Ing_Alto_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Alto_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Alto_upActionPerformed

    private void Ing_Largo_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Largo_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Largo_upActionPerformed

    private void Ing_ActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_ActActionPerformed


            double alto = Double.parseDouble(Ing_Alto_up.getText());
            double largo = Double.parseDouble(Ing_Largo_up.getText());
            double ancho = Double.parseDouble(Ing_Ancho_up.getText());
            int capacidad = Integer.parseInt(Ing_Capacidad_up.getText());
            String categoria = Ing_Categoria_up.getText();
            Seccion sec = new Seccion(ID, alto, largo, ancho, capacidad, categoria);
            sec.ActualizarSeccion();
    }//GEN-LAST:event_Ing_ActActionPerformed

    private void Ing_Categoria_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Categoria_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Categoria_upActionPerformed

    private void Ing_Capacidad_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Capacidad_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Capacidad_upActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Menu_Principal men = new Menu_Principal();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upd_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upd_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upd_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upd_Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upd_Seccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ing_Act;
    private javax.swing.JTextField Ing_Alto_up;
    private javax.swing.JTextField Ing_Ancho_up;
    private javax.swing.JTextField Ing_Capacidad_up;
    private javax.swing.JTextField Ing_Categoria_up;
    private javax.swing.JTextField Ing_Largo_up;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabelIng_Cedula1;
    private javax.swing.JLabel jLabelIng_Cedula2;
    private javax.swing.JLabel jLabelIng_Cedula3;
    private javax.swing.JLabel jLabelIng_Horario;
    private javax.swing.JLabel jLabelIng_Horario1;
    private javax.swing.JLabel jLabelR_Ent;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
