/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interface_;

import karate_project.CConexion;
import karate_project.Cliente;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class Upd_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Upd_Cliente
     */
    public Upd_Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private int ID;

    public void getID(int a) {
        ID = a;
    }

//    public void getInfo(){
//        CConexion con = new CConexion();
//        try {
//            ResultSet RSE = con.Consulta("SELECT * FROM CLIENTE");
//            while (RSE.next()) {
//                Ing_Cedula_up.setText(RSE.getString(2));
//                Ing_Cuota_up.setText(RSE.getString(3));
//                Ing_Horario_up.setText(RSE.getString(4));
//                con.CerrarBD();
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Upd_Cliente.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelR_Ent = new javax.swing.JLabel();
        jLabelIng_Horario = new javax.swing.JLabel();
        jLabelIng_Cedula1 = new javax.swing.JLabel();
        jLabelIng_Cedula2 = new javax.swing.JLabel();
        Ing_Horario_up = new javax.swing.JTextField();
        Ing_Cedula_up = new javax.swing.JTextField();
        Ing_Cuota_up = new javax.swing.JTextField();
        Ing_Actu = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelR_Ent.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelR_Ent.setText("Actualizar Clientes");
        jPanelFondo.add(jLabelR_Ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 33));

        jLabelIng_Horario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Horario.setText("Horario");
        jPanelFondo.add(jLabelIng_Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabelIng_Cedula1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula1.setText("Ingrese Cedula");
        jPanelFondo.add(jLabelIng_Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabelIng_Cedula2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelIng_Cedula2.setText("Ingrese Cuota");
        jPanelFondo.add(jLabelIng_Cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        Ing_Horario_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Horario_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Horario_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 210, -1));

        Ing_Cedula_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Cedula_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Cedula_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, -1));

        Ing_Cuota_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_Cuota_upActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Cuota_up, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 210, -1));

        Ing_Actu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Ing_Actu.setText("Actualizar");
        Ing_Actu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ing_ActuActionPerformed(evt);
            }
        });
        jPanelFondo.add(Ing_Actu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        Regresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanelFondo.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ing_Horario_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Horario_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Horario_upActionPerformed

    private void Ing_Cedula_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Cedula_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Cedula_upActionPerformed

    private void Ing_Cuota_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_Cuota_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ing_Cuota_upActionPerformed

    private void Ing_ActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ing_ActuActionPerformed

        int Cedula = Integer.parseInt(Ing_Cedula_up.getText());
        double Cuota = Double.parseDouble(Ing_Cuota_up.getText());
        String Horario = Ing_Horario_up.getText();
        Cliente cli = new Cliente(ID, Cedula, Cuota, Horario);
        cli.ActualizarCliente();


    }//GEN-LAST:event_Ing_ActuActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        Menu_Principal men = new Menu_Principal();
        men.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Upd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Upd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Upd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Upd_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Upd_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ing_Actu;
    private javax.swing.JTextField Ing_Cedula_up;
    private javax.swing.JTextField Ing_Cuota_up;
    private javax.swing.JTextField Ing_Horario_up;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabelIng_Cedula1;
    private javax.swing.JLabel jLabelIng_Cedula2;
    private javax.swing.JLabel jLabelIng_Horario;
    private javax.swing.JLabel jLabelR_Ent;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
